name: test-depends-on

services:
    web:
        image: nginx:alpine
        container_name: web_app
        # Mencoba koneksi ke DB saat menyala
        # command: >
        #     sh -c "apk add --no-cache postgresql-client &&
        #            echo '=== CHECKING DATABASE CONNECTION ===' &&
        #            pg_isready -h db -U postgres &&
        #            echo '=== DATABASE SIAP, NYALAKAN NGINX ===' &&
        #            nginx -g 'daemon off;'"
        ports:
            - "8080:80"
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:alpine
        container_name: db_postgres
        environment:
            POSTGRES_PASSWORD: secretpassword
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 5s
